import { jsPDF } from 'jspdf';

export const exportToPDF = (entry) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header - Journal Identity
  doc.setFont('serif', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(13, 68, 53); // Emerald
  doc.text('BIOTECHUB | SCIENTIFIC JOURNAL v2.0', margin, 15);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin - 20, 15);
  
  doc.setDrawColor(230, 230, 230);
  doc.line(margin, 18, pageWidth - margin, 18);

  // Title
  doc.setFont('serif', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(26, 26, 26); // Graphite
  const splitTitle = doc.splitTextToSize(entry.title.toUpperCase(), pageWidth - (margin * 2));
  doc.text(splitTitle, margin, 35);

  // Metadata
  doc.setFont('sans', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`IDENTIFIER: ${entry.id}`, margin, 50);
  doc.text(`ENTRY TYPE: ${entry.type}`, margin, 55);
  doc.text(`DATE: ${entry.date}`, margin, 60);

  // Content
  doc.setFont('sans', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  const splitContent = doc.splitTextToSize(entry.content, pageWidth - (margin * 2));
  doc.text(splitContent, margin, 75);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This document is a formal scientific record generated by BiotecHub ELN Node.', margin, doc.internal.pageSize.getHeight() - 10);

  doc.save(`${entry.id}_paper.pdf`);
};
